parameters:
    appbundle.menu_listener.class: AppBundle\EventListener\MenuListener
    appbundle.show_user_listener.class: AppBundle\EventListener\ShowUserListener



services:
    appbundle.twig.fontawesomebrand:
        class: AppBundle\Twig\FontAwesomeIconExtension
        public: false
        tags:
            - { name: twig.extension }

    appbundle.foslistener:
        class: AppBundle\EventListener\FOSListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    appbundle.menu_listener:
        class: %appbundle.menu_listener.class%
        arguments: [ '@translator', "@=service('security.token_storage')" ]
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }

    appbundle.show_user_listener:
        class: %appbundle.show_user_listener.class%
        arguments: [ '@translator', "@=service('security.token_storage')" ]
        tags:
            - { name: kernel.event_listener, event: theme.sidebar_user, method: onShowUser}

    appbundle.group_voter:
        class: AppBundle\Security\GroupVoter
        arguments: [ '@doctrine.orm.entity_manager' ]
        tags:
            - { name: security.voter }
        public: false


    appbundle.field_protect:
        class: AppBundle\Util\FieldProtect
        arguments: ['@appbundle.key_protect']

    appbundle.key_protect:
        class: AppBundle\Util\KeyProtect
        arguments: ['@request_stack', '@security.token_storage', '@appbundle.user_group_repository']

    appbundle.user_group_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments: [AppBundle\Entity\UserGroup]


    # JSON Encoder
    appbundle.encoder.json:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder

    appbundle.normalizer.login:
        class: AppBundle\Serializer\Normalizer\LoginNormalizer
        arguments: ['@appbundle.field_protect']

    appbundle.serializer.default:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            0:
                - '@appbundle.normalizer.login'
                - '@serializer.normalizer.object'
            1:
                - '@appbundle.encoder.json'